services:
  - type: web
    name: playstore-cms
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_COOKIE_SECURE
        value: "true"
      - key: PYTHON_VERSION
        value: "3.13.0"
      - key: UPLOAD_DIR
        value: /opt/render/project/src/uploads
      - key: MAX_UPLOAD_SIZE
        value: "104857600"
